"""Shared Pydantic models for the AI Search pipeline."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class SearchMode(StrEnum):
    """Search modality selector.

    TEXT  — 3-vector RRF (semantic + structural + style) text-to-image.
    IMAGE — GPT-4o extraction + 4-vector RRF (3 text + image) image-to-image.
    """

    TEXT = "text"
    IMAGE = "image"


class CharacterDescription(BaseModel):
    """Per-character structured descriptions for embedding."""

    character_id: str = Field(
        description="Character's proper name in lowercase, e.g. 'hanuman', "
        "'lord_rama', 'sita', 'ravana'. Use descriptive identifier only "
        "when no name is identifiable, e.g. 'warrior_blue_armor'."
    )
    semantic: str = Field(
        description="2-3 sentences: identity by proper name, mythological "
        "role, specific costume/attire worn, jewelry/ornaments visible, "
        "weapons/props held (gada, bow, arrows, torch, mountain), "
        "character form or avatar (giant, multi-headed, blue-skinned)"
    )
    emotion: str = Field(
        description="2-3 sentences: emotional expression (fury, devotion, "
        "sorrow, triumph), body language cues, intensity of emotion"
    )
    pose: str = Field(
        description="2-3 sentences: specific action being performed "
        "(flying, fighting, kneeling, lifting), physical position, "
        "orientation, gestures, interaction with other characters or objects"
    )


class ImageMetadata(BaseModel):
    """Synthetic metadata generated by LLM."""

    scene_type: str
    time_of_day: str
    lighting_condition: str
    primary_subject: str
    secondary_subjects: list[str] = Field(default_factory=list)
    character_action: str = Field(
        default="",
        description="Primary action verb: flying, fighting, kneeling, "
        "lifting, burning, meditating, blessing, mourning, charging",
    )
    weapons_props: list[str] = Field(
        default_factory=list,
        description="Weapons and props visible: gada, bow, arrows, trident, "
        "mountain, torch, chariot, chakra, lotus, crown, mace",
    )
    location_name: str = Field(
        default="",
        description="Named location: Lanka, Ayodhya, Kishkindha, Ashoka Vatika, "
        "Dandaka forest, Ram Setu, sky, ocean, palace, battlefield",
    )
    episode_name: str = Field(
        default="",
        description="Named story episode: Lanka Dahan, Sanjeevani quest, "
        "Setu Bandhan, Sita Haran, Swayamvar, Agni Pariksha, Bali Vadh",
    )
    artistic_style: str
    color_palette: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    narrative_theme: str


class NarrativeIntent(BaseModel):
    """Narrative analysis of the image."""

    story_summary: str
    narrative_type: str  # cinematic, documentary, surreal, fantasy, etc.
    tone: str


class EmotionalTrajectory(BaseModel):
    """Emotional trajectory analysis."""

    starting_emotion: str
    mid_emotion: str
    end_emotion: str
    emotional_polarity: float = Field(ge=-1.0, le=1.0)


class RequiredObjects(BaseModel):
    """Objects detected in the scene."""

    key_objects: list[str] = Field(default_factory=list)
    contextual_objects: list[str] = Field(default_factory=list)
    symbolic_elements: list[str] = Field(default_factory=list)


class LowLightMetrics(BaseModel):
    """Low-light robustness indicators."""

    brightness_score: float = Field(ge=0.0, le=1.0)
    contrast_score: float = Field(ge=0.0, le=1.0)
    noise_estimate: float = Field(ge=0.0, le=1.0)
    shadow_dominance: float = Field(ge=0.0, le=1.0)
    visibility_confidence: float = Field(ge=0.0, le=1.0)


class ImageExtraction(BaseModel):
    """Complete GPT-4o vision extraction output (used as structured output schema)."""

    semantic_description: str = Field(
        description="250-word description covering: named characters, specific "
        "actions, weapons/props, costumes/jewelry, character form/avatar, "
        "location, story episode, emotional tone, and scale relationships"
    )
    structural_description: str = Field(
        description="150-word spatial composition: character positioning, scale "
        "relationships, camera angle, action direction, depth staging"
    )
    style_description: str = Field(
        description="150-word artistic treatment: color palette, lighting type, "
        "texture, atmosphere, rendering approach, cultural art conventions"
    )
    characters: list[CharacterDescription] = Field(default_factory=list)
    metadata: ImageMetadata
    narrative: NarrativeIntent
    emotion: EmotionalTrajectory
    objects: RequiredObjects
    low_light: LowLightMetrics


class ImageVectors(BaseModel):
    """All embedding vectors for an image."""

    semantic_vector: list[float]
    structural_vector: list[float]
    style_vector: list[float]
    image_vector: list[float] = Field(default_factory=list)


class SearchDocument(BaseModel):
    """Document structure for Azure AI Search index upload."""

    image_id: str
    generation_prompt: str
    image_url: str = ""
    scene_type: str
    time_of_day: str
    lighting_condition: str
    primary_subject: str
    character_action: str = ""
    weapons_props: list[str] = Field(default_factory=list)
    location_name: str = ""
    episode_name: str = ""
    artistic_style: str
    tags: list[str]
    narrative_theme: str
    narrative_type: str
    emotional_polarity: float
    low_light_score: float
    character_count: int
    metadata_json: str  # Full metadata as JSON string for retrieval
    extraction_json: str  # Full extraction as JSON string for re-ranking

    # Vectors (populated by embedding pipeline)
    semantic_vector: list[float] = Field(default_factory=list)
    structural_vector: list[float] = Field(default_factory=list)
    style_vector: list[float] = Field(default_factory=list)
    image_vector: list[float] = Field(default_factory=list)


class SearchResult(BaseModel):
    """Single search result with scores."""

    image_id: str
    search_score: float
    generation_prompt: str | None = None
    image_url: str | None = None
    scene_type: str | None = None
    tags: list[str] = Field(default_factory=list)
