"""Shared Pydantic models for the AI Search pipeline."""

from __future__ import annotations

from pydantic import BaseModel, Field


class CharacterDescription(BaseModel):
    """Per-character structured descriptions for embedding."""

    character_id: str = Field(description="Descriptive identifier, e.g. 'woman_red_dress'")
    semantic: str = Field(description="2-3 sentences: identity, role, appearance, clothing")
    emotion: str = Field(description="2-3 sentences: emotional expression, body language cues")
    pose: str = Field(description="2-3 sentences: physical position, orientation, gestures")


class ImageMetadata(BaseModel):
    """Synthetic metadata generated by LLM."""

    scene_type: str
    time_of_day: str
    lighting_condition: str
    primary_subject: str
    secondary_subjects: list[str] = Field(default_factory=list)
    artistic_style: str
    color_palette: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    narrative_theme: str


class NarrativeIntent(BaseModel):
    """Narrative analysis of the image."""

    story_summary: str
    narrative_type: str  # cinematic, documentary, surreal, fantasy, etc.
    tone: str


class EmotionalTrajectory(BaseModel):
    """Emotional trajectory analysis."""

    starting_emotion: str
    mid_emotion: str
    end_emotion: str
    emotional_polarity: float = Field(ge=-1.0, le=1.0)


class RequiredObjects(BaseModel):
    """Objects detected in the scene."""

    key_objects: list[str] = Field(default_factory=list)
    contextual_objects: list[str] = Field(default_factory=list)
    symbolic_elements: list[str] = Field(default_factory=list)


class LowLightMetrics(BaseModel):
    """Low-light robustness indicators."""

    brightness_score: float = Field(ge=0.0, le=1.0)
    contrast_score: float = Field(ge=0.0, le=1.0)
    noise_estimate: float = Field(ge=0.0, le=1.0)
    shadow_dominance: float = Field(ge=0.0, le=1.0)
    visibility_confidence: float = Field(ge=0.0, le=1.0)


class ImageExtraction(BaseModel):
    """Complete GPT-4o vision extraction output (used as structured output schema)."""

    semantic_description: str = Field(description="Rich 200-word description for semantic embedding")
    structural_description: str = Field(
        description="150-word spatial/composition analysis for structural embedding"
    )
    style_description: str = Field(description="150-word artistic style analysis for style embedding")
    characters: list[CharacterDescription] = Field(default_factory=list)
    metadata: ImageMetadata
    narrative: NarrativeIntent
    emotion: EmotionalTrajectory
    objects: RequiredObjects
    low_light: LowLightMetrics


class ImageVectors(BaseModel):
    """All embedding vectors for an image."""

    semantic_vector: list[float]
    structural_vector: list[float]
    style_vector: list[float]
    image_vector: list[float] = Field(default_factory=list)


class SearchDocument(BaseModel):
    """Document structure for Azure AI Search index upload."""

    image_id: str
    generation_prompt: str
    scene_type: str
    time_of_day: str
    lighting_condition: str
    primary_subject: str
    artistic_style: str
    tags: list[str]
    narrative_theme: str
    narrative_type: str
    emotional_polarity: float
    low_light_score: float
    character_count: int
    metadata_json: str  # Full metadata as JSON string for retrieval
    extraction_json: str  # Full extraction as JSON string for re-ranking

    # Vectors (populated by embedding pipeline)
    semantic_vector: list[float] = Field(default_factory=list)
    structural_vector: list[float] = Field(default_factory=list)
    style_vector: list[float] = Field(default_factory=list)
    image_vector: list[float] = Field(default_factory=list)


class SearchResult(BaseModel):
    """Single search result with scores."""

    image_id: str
    search_score: float
    generation_prompt: str | None = None
    scene_type: str | None = None
    tags: list[str] = Field(default_factory=list)
